name: CTCollection
version: '${project.version}'
main: me.msicraft.ctcollection.CTCollection
api-version: '1.20'
commands:
  도감:
    description: main command
  ctcollection:
    description: sub command
    aliases: [collection, ctco]